services:
  bartter-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      bartter-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./app_data:/app_data
  bartter-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/main/resources/sql/dml/location.sql:/docker-entrypoint-initdb.d/location.sql
      - ./src/main/resources/sql/dml/cropcategory.sql:/docker-entrypoint-initdb.d/cropcategory.sql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
